### ISSUE TITLE
How to deploy this on server ?

### ISSUE THREAD

**Issue by tradingplatfroms** [JacobGrisham/Commerce-Full-Stack-Web-App-using-Django#1]
any instructions?

**Comment by JacobGrisham** [comment]
Hello,

Thank you for your interest. However, I am not offering a license for this repository. As such, this repository exists just as a means to view the code I wrote. Details for how to run or deploy are out of scope.

**Comment by jontstaz** [comment]
1. pipenv install
2. python manage.py migrate
3. python manage.py createsuperuser
4. python manage.py runserver
